version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logme
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s

  app:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    container_name: logme-backend
    expose:
      - "6666"
    ports:
      - "6666:6666"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env


volumes:
  postgres:
    name: nest-prisma-docker-db