version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logme
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
    networks: 
    - nginx_network

  app:
    environment:
      - NODE_ENV=production
    networks:
      - nginx_network
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    #seems not to be working
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    container_name: logme-backend
    expose:
      - "8200"
    ports:
      - "8200:8200"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

networks:
  nginx_network:
    external:
      name: dockernet

volumes:
  postgres:
    name: nest-prisma-docker-db